// <auto-generated />
namespace MVCAlmacen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class population_company : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(population_company));
        
        string IMigrationMetadata.Id
        {
            get { return "201804292158312_population_company"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
